base_url = "https://collaborative-intelligence-workshop.github.io"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true
theme = "academic-workshop"
ignored_static = ["sponsorship_prospectus.pdf","travel-support-CVs/*"]

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
title = {tagline = "RSS workshop on", title = "Collaborative Intelligence", subtitles = ["Los Angeles, California, United States", "June 23, 2025"]}
banner = {extension = "svg", size = "fit-height", fade = true}
header_pages = [{name = "Home", url = "/#home"},{name = "Schedule", url = "/#schedule"}]
